services:
  # Define serviço de back-end
  - type: web
    name: afroconnection-backend
    # Define o ambiente como Java
    env: java
    # Diretório raiz
    rootDir: backend
    # Comandos para construir e iniciar a aplicação
    buildCommand: "./mvnw package"
    startCommand: "java -jar target/backend-0.0.1-SNAPSHOT.jar"
    # Configuração do plano gratuito
    plan: free
    # Variáveis de ambiente para o banco de dados
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://db.wxrfjqybudekpzqsukzm.supabase.co:5432/postgres
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        value: AfroConnection-DB
      - key: JWT_SECRET
        value: Y1Jvb25lY3Rpb25TZWNyZXRLZXlGb3JBdXRoZW50aWNhdGlvbkFuZEF1dGhvcml6YXRpb24=
      - key: SPRING_JPA_DATABASE-PLATFORM
        value: org.hibernate.dialect.PostgreSQLDialect
