services:
  - type: web
    name: afroconnection-backend
    runtime: java
    rootDir: backend
    buildCommand: "./mvnw package"
    startCommand: "java -jar target/backend-0.0.1-SNAPSHOT.jar"
    plan: free
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://db.wxrfjqybudekpzqsukzm.supabase.co:5432/postgres
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        value: AfroConnection-DB
      - key: JWT_SECRET
        value: Y1Jvb25lY3Rpb25TZWNyZXRLZXlGb3JBdXRoZW50aWNhdGlvbkFuZEF1dGhvcml6YXRpb24=
      - key: SPRING_JPA_DATABASE-PLATFORM
        value: org.hibernate.dialect.PostgreSQLDialect
